sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
script:
- "./gradlew check"
- "./gradlew assemble"
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- "./gradlew buildDocker"
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app: event-rock