sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- "./gradlew buildDocker"
after_success:
- docker login --username="$HEROKU_EMAIL" --password="$HEROKU_PASSWORD" registry.heroku.com
- docker tag eventrock/eventrock registry.heroku.com/event-rock/web
- docker push registry.heroku.com/event-rock/web