language: java
jdk:
- oraclejdk8
script:
  - ./gradlew check
  - ./gradlew assemble
#  - ./gradlew buildDocker
deploy:
  provider: heroku
  api_key:
    secure: N/Q9PMj/EHboc30c4onEOn5WoIll3UQt5atRQKCLI2PZKcgx+47W70BM58Av60qZgh9rLwJG0nUHkZM2YsZfSNrUgtzuHW8CyFW54F4vBv5LF6SnbK6ukTo67H81mjsOH6jZt0yL3AMCUhroz2m9/VY97JlD5xKCSn+yERVxoEsvJefGIh5dsqPaPhuqRqjjQrPir1GmQ8xBZiOygUoEfJpipm7CGPoa8JlBmKcYnZBgBDNvew+z1g0/QGKWgft8ymR8+RS3Q7506guydsW5TsFbTxLf/7F0g7wMKZs55z7OLDbjPg3RfKmqbhd2Q7OjIW8ige99S2M43G6Ng8gY5ToFt3W4SeHdy5PivL7HJH1/Ntwu7gMW6ZwtbTk0lzOtDYBlqqk2J25OS8usZhQ/vPUFQWH2tyQHCKgnZRx4ZNGgHJGG0+g8IojxO+2JrZG7q5OjaWmNkscQqQhE9isJzG9F6swrF87aNlZO9YZqXE23lwg+eeC4xgGAvGFaZsC1xh4sQD+K7fCSBnqJJq+UxF7sqyoLOJOQNXngHVIU0k05A4qNAxCJJmi15sK3ju+3dBeegWJU1rmQsrKs0OPo2gRBFHRbf8RsTkQP9CQeQbjq6IlfgRM1HZZjN0cJOtZCB3nQeIOx1GXbeaO9RxvzrLcNvc8TS09aHlLfINj+cCE=
  app: eventrock
