security:
    ignored: =/**
    basic:
      enable: false

server:
  port: ${port}

spring:
    datasource:
        username: bc71ae9f0e841e
        password: 3f0cebd3
        url: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/heroku_6f766f8a99167ac?nullNamePatternMatchesAll=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true&serverTimezone=Asia/Bangkok&useTimezone=true&reconnect=true
        driverClassName: com.mysql.cj.jdbc.Driver