spring:
    datasource:
        url: jdbc:h2:file:./build/h2db/db/eventrock;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        platform: h2
        username: sa
        password:
        driverClassName: org.h2.Driver

    h2:
      console:
          enabled: true
          path: /h2-console

liquibase:
  drop-first: true