spring:
    datasource:
        url: jdbc:h2:~/eventrock;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        platform: h2
        username: sa
        password:

    h2:
      console:
          enabled: true
          path: /h2-console